#!/bin/sh
# Prepares generated inputs for the simulator build in $1 (default sim/build/gen):
#   i18n/        English-only I18n tables generated by scripts/gen_i18n.py
#   third_party/ ArduinoJson (pinned to the firmware's 7.4.2)
# Never writes into the repo's own lib/ tree.
set -e
SIM_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
REPO="$(CDPATH= cd -- "$SIM_DIR/.." && pwd)"
GEN="${1:-$SIM_DIR/build/gen}"
AJSON_VERSION=7.4.2

mkdir -p "$GEN/i18n" "$GEN/third_party"

stamp="$GEN/i18n/.stamp"
newest=$(find "$REPO/lib/I18n" "$REPO/scripts/gen_i18n.py" -newer "$stamp" 2>/dev/null | head -1 || true)
if [ ! -f "$stamp" ] || [ -n "$newest" ]; then
  echo "[sim] generating English-only I18n tables"
  cp "$REPO/lib/I18n/I18n.h" "$REPO/lib/I18n/I18n.cpp" "$GEN/i18n/"
  python3 "$REPO/scripts/gen_i18n.py" "$REPO/lib/I18n/translations" "$GEN/i18n" --builtin-langs en >/dev/null
  touch "$stamp"
fi

if [ ! -f "$GEN/third_party/ArduinoJson.h" ]; then
  local_copy=$(ls -d "$REPO"/.pio/libdeps/*/ArduinoJson 2>/dev/null | head -1 || true)
  if [ -n "$local_copy" ] && grep -q "\"version\": \"$AJSON_VERSION\"" "$local_copy/library.json" 2>/dev/null; then
    echo "[sim] using ArduinoJson from $local_copy"
    cp -R "$local_copy/src/." "$GEN/third_party/"
  else
    echo "[sim] downloading ArduinoJson $AJSON_VERSION"
    curl -fsSL -o "$GEN/third_party/ArduinoJson.h" \
      "https://github.com/bblanchon/ArduinoJson/releases/download/v$AJSON_VERSION/ArduinoJson-v$AJSON_VERSION.h"
  fi
fi
